import { c as createComponent, r as renderTemplate, d as renderComponent, m as maybeRenderHead } from '../../chunks/astro/server_MQ-OKnVF.mjs';
import 'kleur/colors';
import 'html-escaper';
import { $ as $$Layout } from '../../chunks/Layout_DWONt-1M.mjs';
import { $ as $$Header } from '../../chunks/Header_DgcknLtB.mjs';
import { $ as $$FloatingActionButton } from '../../chunks/FloatingActionButton_DlOUReT-.mjs';
import { $ as $$BlogContactCTA } from '../../chunks/BlogContactCTA_C4DZZiuU.mjs';
/* empty css                                                                        */
export { renderers } from '../../renderers.mjs';

const $$HowToGet10XEffortFromYourEmployees = createComponent(($$result, $$props, $$slots) => {
  const blogPost = {
    title: "How to Get 10x Effort From Your Employees",
    date: "June 10, 2025",
    author: "Jonathon Broce"
  };
  return renderTemplate`${renderComponent($$result, "Layout", $$Layout, { "title": `${blogPost.title} - Day 41 Thrive`, "data-astro-cid-6vbskvpj": true }, { "default": ($$result2) => renderTemplate` ${renderComponent($$result2, "Header", $$Header, { "data-astro-cid-6vbskvpj": true })} ${maybeRenderHead()}<main class="blog-post" data-astro-cid-6vbskvpj> <article class="container" data-astro-cid-6vbskvpj> <header class="post-header" data-astro-cid-6vbskvpj> <h1 data-astro-cid-6vbskvpj>${blogPost.title}</h1> <div class="post-meta" data-astro-cid-6vbskvpj> <span class="date" data-astro-cid-6vbskvpj>${blogPost.date}</span> <span class="author" data-astro-cid-6vbskvpj>By ${blogPost.author}</span> </div> <p class="subtitle" data-astro-cid-6vbskvpj>(Hint: Most Start at 0.8x Just Doing the Bare Minimum)</p> </header> <div class="post-content" data-astro-cid-6vbskvpj> <h2 data-astro-cid-6vbskvpj>Introduction: Stop Expecting More—Start Unlocking It</h2> <p data-astro-cid-6vbskvpj>Here's a hard truth most leaders don't want to say out loud:</p> <p data-astro-cid-6vbskvpj>Most employees aren't giving 100%.<br data-astro-cid-6vbskvpj>
They're giving just enough not to get fired.</p> <p data-astro-cid-6vbskvpj>If you're lucky, they're at a 1x output—meeting expectations, checking boxes, doing their "job."</p> <p data-astro-cid-6vbskvpj>But the goal isn't compliance.<br data-astro-cid-6vbskvpj>
The goal is commitment.</p> <p data-astro-cid-6vbskvpj>At Day 41 Thrive, and in Don't GUESS, Thrive Through Storms, we teach leaders how to unlock effort, not demand it—because people don't go 10x for companies.<br data-astro-cid-6vbskvpj>
They go 10x for leaders who believe in them and show them the way.</p> <p data-astro-cid-6vbskvpj>Here's how to shift from transactional output to transformational effort.</p> <h2 data-astro-cid-6vbskvpj>1. Know the Real Starting Line: &lt;1x Effort Is Normal</h2> <p data-astro-cid-6vbskvpj>Most leaders assume people start at 1x effort.<br data-astro-cid-6vbskvpj>
But the reality? Most start at 0.8x—just doing the basics:</p> <ul data-astro-cid-6vbskvpj> <li data-astro-cid-6vbskvpj>Punching in on time</li> <li data-astro-cid-6vbskvpj>Avoiding big mistakes</li> <li data-astro-cid-6vbskvpj>Responding only when asked</li> </ul> <p data-astro-cid-6vbskvpj>Why? Because:</p> <ul data-astro-cid-6vbskvpj> <li data-astro-cid-6vbskvpj>They're not bought in</li> <li data-astro-cid-6vbskvpj>They don't know the "why"</li> <li data-astro-cid-6vbskvpj>No one's ever led them past average</li> </ul> <p data-astro-cid-6vbskvpj>That's not laziness. That's leadership waiting to happen.</p> <p data-astro-cid-6vbskvpj>You don't raise effort with pressure. You raise it with purpose.</p> <h2 data-astro-cid-6vbskvpj>2. Activate Identity Before You Expect Performance</h2> <p data-astro-cid-6vbskvpj>From Don't GUESS, Thrive Through Storms:</p> <p data-astro-cid-6vbskvpj>"You can't grow someone into the next level if they don't see themselves there."</p> <p data-astro-cid-6vbskvpj>If someone only sees themselves as a laborer, don't expect them to think like a leader.</p> <p data-astro-cid-6vbskvpj>Ask yourself:</p> <ul data-astro-cid-6vbskvpj> <li data-astro-cid-6vbskvpj>Do they know the mission they're a part of?</li> <li data-astro-cid-6vbskvpj>Do they know how their role creates impact?</li> <li data-astro-cid-6vbskvpj>Do they feel trusted to grow?</li> </ul> <p data-astro-cid-6vbskvpj>When you activate identity, you unlock effort.<br data-astro-cid-6vbskvpj>
People rise to the level of how you see them—and remind them.</p> <h2 data-astro-cid-6vbskvpj>3. Turn Effort Into Ownership with the G.U.E.S.S. Framework</h2> <p data-astro-cid-6vbskvpj>From the G.U.E.S.S. model:</p> <ul data-astro-cid-6vbskvpj> <li data-astro-cid-6vbskvpj>GROW: Self-reflect, expand, evolve, develop</li> <li data-astro-cid-6vbskvpj>UNLEASH: Recognize, inspire, support, empower</li> <li data-astro-cid-6vbskvpj>ENHANCE: Focus, leverage, optimize, work smart</li> <li data-astro-cid-6vbskvpj>STRATEGIZE: Specific, measurable, achievable, relevant, time-bound</li> <li data-astro-cid-6vbskvpj>SYNCHRONIZE: Trust, engage, align, mobilize</li> </ul> <p data-astro-cid-6vbskvpj>10x effort doesn't come from hype.<br data-astro-cid-6vbskvpj>
It comes from structure that guides performance and belief that fuels it.</p> <p data-astro-cid-6vbskvpj>You're not just trying to manage effort.<br data-astro-cid-6vbskvpj>
You're shaping it—one clear step at a time.</p> <p data-astro-cid-6vbskvpj>You're not building employees. You're building champions.</p> <h2 data-astro-cid-6vbskvpj>4. Create a Culture of Safe Stretching</h2> <p data-astro-cid-6vbskvpj>You want 10x effort?<br data-astro-cid-6vbskvpj>
Give people safe spaces to fail and grow.</p> <ul data-astro-cid-6vbskvpj> <li data-astro-cid-6vbskvpj>Reward initiative, not just results</li> <li data-astro-cid-6vbskvpj>Celebrate effort, not just output</li> <li data-astro-cid-6vbskvpj>Review decisions, not just mistakes</li> </ul> <p data-astro-cid-6vbskvpj>People don't fear effort.<br data-astro-cid-6vbskvpj>
They fear looking dumb, being punished, or getting left behind.</p> <p data-astro-cid-6vbskvpj>Build a culture where trying hard is the expectation, not the exception.</p> <h2 data-astro-cid-6vbskvpj>5. Respect That They'll Never Be You (And That's a Good Thing)</h2> <p data-astro-cid-6vbskvpj>Here's something every founder and leader needs to hear:</p> <p data-astro-cid-6vbskvpj>No employee will ever be you.<br data-astro-cid-6vbskvpj>
And they shouldn't be.</p> <p data-astro-cid-6vbskvpj>They didn't risk everything. They don't wake up at 3AM thinking about payroll.<br data-astro-cid-6vbskvpj>
They aren't obsessed with the mission—and that's okay.</p> <p data-astro-cid-6vbskvpj>Your team should be able to:</p> <ul data-astro-cid-6vbskvpj> <li data-astro-cid-6vbskvpj>Work hard from 9 to 5</li> <li data-astro-cid-6vbskvpj>Clock out without guilt</li> <li data-astro-cid-6vbskvpj>Go home and be with their family</li> </ul> <p data-astro-cid-6vbskvpj>So stop:</p> <ul data-astro-cid-6vbskvpj> <li data-astro-cid-6vbskvpj>Sending late-night texts</li> <li data-astro-cid-6vbskvpj>Shooting off early-morning emails</li> <li data-astro-cid-6vbskvpj>Expecting them to live and breathe the business</li> </ul> <p data-astro-cid-6vbskvpj>You'll burn them out.</p> <p data-astro-cid-6vbskvpj>When people are trusted, protected, and given margin, effort multiplies.</p> <p data-astro-cid-6vbskvpj>Create a culture where people are allowed to:</p> <ul data-astro-cid-6vbskvpj> <li data-astro-cid-6vbskvpj>Try and fail</li> <li data-astro-cid-6vbskvpj>Log off on time</li> <li data-astro-cid-6vbskvpj>Be human</li> </ul> <p data-astro-cid-6vbskvpj>And most importantly, set boundaries and stick to them.<br data-astro-cid-6vbskvpj>
If you want high performance, model sustainable leadership.</p> <h2 data-astro-cid-6vbskvpj>6. Incentivize Behavior, Not Just Results</h2> <p data-astro-cid-6vbskvpj>Most companies reward production and sales only.</p> <p data-astro-cid-6vbskvpj>But if you want to build a 10x culture:</p> <ul data-astro-cid-6vbskvpj> <li data-astro-cid-6vbskvpj>Recognize problem-solvers</li> <li data-astro-cid-6vbskvpj>Celebrate teammates who support others</li> <li data-astro-cid-6vbskvpj>Reward great communication and ownership</li> </ul> <p data-astro-cid-6vbskvpj>"We don't just value what you do. We value how you show up."</p> <h2 data-astro-cid-6vbskvpj>7. Multiply What's Working</h2> <p data-astro-cid-6vbskvpj>Find your 2x, 3x, and 5x players—and figure out what they're doing differently.</p> <p data-astro-cid-6vbskvpj>Then:</p> <ul data-astro-cid-6vbskvpj> <li data-astro-cid-6vbskvpj>Share their stories</li> <li data-astro-cid-6vbskvpj>Create teachable moments</li> <li data-astro-cid-6vbskvpj>Turn habits into systems</li> </ul> <p data-astro-cid-6vbskvpj>Effort is contagious. Shine the spotlight on it.</p> <h2 data-astro-cid-6vbskvpj>Final Thought: You Don't Need Clones. You Need Champions.</h2> <p data-astro-cid-6vbskvpj>If you're expecting your team to care like the founder, you're setting them up to fail.</p> <p data-astro-cid-6vbskvpj>But if you give them the tools, the trust, and the training—they'll give you more than compliance.<br data-astro-cid-6vbskvpj>
They'll give you commitment.</p> <p data-astro-cid-6vbskvpj>Effort multiplies in cultures that are clear, kind, and consistent.</p> <p data-astro-cid-6vbskvpj>So:</p> <ul data-astro-cid-6vbskvpj> <li data-astro-cid-6vbskvpj>Train with purpose</li> <li data-astro-cid-6vbskvpj>Lead with trust</li> <li data-astro-cid-6vbskvpj>Honor their time</li> <li data-astro-cid-6vbskvpj>Stop measuring value by who "acts like the owner"</li> </ul> <p data-astro-cid-6vbskvpj>This is how you build teams that thrive through storms—without burning out in them.</p> <p data-astro-cid-6vbskvpj>Day 41 Thrive — Lead Better. Grow Stronger. Thrive Longer.</p> ${renderComponent($$result2, "BlogContactCTA", $$BlogContactCTA, { "data-astro-cid-6vbskvpj": true })} </div> </article> </main> ${renderComponent($$result2, "FloatingActionButton", $$FloatingActionButton, { "data-astro-cid-6vbskvpj": true })} ` })} `;
}, "/Users/sandy/Downloads/project 2/src/pages/blog/how-to-get-10x-effort-from-your-employees.astro", void 0);

const $$file = "/Users/sandy/Downloads/project 2/src/pages/blog/how-to-get-10x-effort-from-your-employees.astro";
const $$url = "/blog/how-to-get-10x-effort-from-your-employees";

const _page = /*#__PURE__*/Object.freeze(/*#__PURE__*/Object.defineProperty({
    __proto__: null,
    default: $$HowToGet10XEffortFromYourEmployees,
    file: $$file,
    url: $$url
}, Symbol.toStringTag, { value: 'Module' }));

const page = () => _page;

export { page };
